<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.gitee.yunjiao-source.spring-boot</groupId>
        <artifactId>dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../dependencies/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>starters</artifactId>
    <packaging>pom</packaging>
    <name>Spring Boot :: Starters</name>
    <description>Starters启动器</description>

    <modules>
        <module>starter-id</module>
        <module>starter-querydsl-sql</module>
        <module>starter-querydsl-jpa</module>
        <module>starter-apijson-fastjson2</module>
        <module>starter-apijson-gson</module>
        <module>starter-captcha</module>
        <module>starter-tika</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>