[[id]]
== ID扩展

ID生成是企业信息系统需要的，重要的，必须的功能。目前使用雪花算法生成ID是最流行的，本框架集成`Hutool`，`uid-generator`等框架，
这些框架实现了雪花算法。

[NOTE]
====
`uid-generator`框架（ https://gitee.com/baidu/uid-generator[官网] ）是百度开源的，此框架没有发布到Maven中心仓库，所以
在pom中无法引入。本框架引入的是`uid-core`包 （ https://gitee.com/syecao/uid-generator-starter[官网] ）
====

雪花算法需要一个中心化服务分配机器ID，在不同的应用中实现统一的ID（不重复），但这并不常见，实现也很复杂。一般情况下，比如在用户应用与订单应用，
用户表的ID与订单表的ID是可以重复的。

在微服务场景中，需要在多台服务器上部署相同的应用，如用户应用，必须保证每个用户应用新增用户的ID是不重复的。

根据以上分析，可以把每台服务当做中心化服务，分配机器ID。只需要在系统定义环境变量，雪花ID算法工具获取环境变量，就可以保证相同的应用统一的ID（不重复），
这个思路我称为`有限的分布式ID`。 本框架实现了`有限的分布式ID`， 支持在系统中定义环境变量`SNOWFLAKE_WORKER_ID`和`SNOWFLAKE_DATACENTER_ID`。

[TIP]
====
如果需要真正的分布式ID，推荐`uid-generator-starter` （ https://gitee.com/syecao/uid-generator-starter[官网] ）, 它支持中心化服务，如
数据库，redis， zk等
====

****
.雪花ID算法
是一个在分布式系统中广泛使用的全局唯一ID生成算法，由Twitter公司提出，旨在解决在分布式环境下高并发、高性能地生成唯一ID的问题

优点

* 全局唯一：通过时间戳+机器ID+序列号的组合，在分布式系统下几乎不可能重复。
* 趋势递增：由于时间戳在最前面，生成的ID整体上是随时间递增的。这对于数据库索引（如MySQL的B+Tree）非常友好，插入性能高。
* 高性能：本地生成，无需远程调用数据库或Redis等中间件，速度极快（每毫秒每台机器可生成4096个ID）。
* 无需中心化服务：不像UUID需要中心化的发号器，避免了单点故障和性能瓶颈。（但分配机器ID可能需要一个中心化服务）。
* 信息隐含：ID本身包含时间戳和机器ID信息，在排查问题时可以根据ID反推出生成时间和生成机器。

(信息来源：DeepSeek)
****

****
.示例
Gitee: https://gitee.com/yunjiao-source/yunjiao-spring-boot/tree/master/examples/example-id[examples/example-id]
****

[[id-rhsy]]
=== 如何使用

在pom.xml文件中添加
[source,xml,indent=0]
[subs="verbatim,quotes"]
----
        <dependency>
            <groupId>io.gitee.yunjiao-source.spring-boot</groupId>
            <artifactId>starter-id</artifactId>
        </dependency>
----

[[id-pzzn]]
=== 配置指南

在`application.yml`中配置参数

|===
| 配置参数 | 默认值 | 说明

| spring.id.uid-generator.time-bits
| 28
|

| spring.id.uid-generator.worker-bits
| 22
|

| spring.id.uid-generator.seq-bits
| 13
|

| spring.id.uid-generator.epoch-str
| 2025-08-20
|

|===

[[id-kfzn]]
=== 开发指南

在服务中注入
[source,java,indent=0]
[subs="verbatim,quotes"]
----
@Slf4j
@Component
public class IdCommandLineRunner implements CommandLineRunner {
    @Autowired
    private Snowflake snowflake;
    @Autowired
    private UidGeneratorCached uidGeneratorCached;
    @Autowired
    private UidGeneratorDefault uidGeneratorDefault;

    @Override
    public void run(String... args) throws Exception {
        TimeUnit.SECONDS.sleep(3);

        log.info("Snowflake = {}",  generator(() -> snowflake.nextId()).size());
        log.info("uidGeneratorCached = {}", generator(() -> uidGeneratorCached.getUID()).size() );
        log.info("uidGeneratorDefault = {}", generator(() -> uidGeneratorDefault.getUID()).size() );
    }

    private Set<Long> generator(Supplier<Long> supplier) {
        return IntStream.range(0, 4000).mapToObj(i -> supplier.get())
                .peek(l -> System.out.print(l + ","))
                .collect(Collectors.toSet());
    }
}
----

在使用中，日志中会出现警告信息
[source,console,indent=0]
----
WARN   --- [           main] y.s.e.i.u.EnvironmentWorkerIdAssigner    : Uid-Generator 框架雪花算法配置使用默认参数。如需支持分布式，请设置系统环境变量：'yunjiao.springboot.extension.id.snowflakeWorkId'
WARN   --- [           main] y.s.a.id.HutoolIdConfiguration           : Hutool 框架雪花算法配置使用默认参数。如需支持分布式，请设置系统环境变量：'yunjiao.springboot.extension.id.snowflakeWorkId' 与 'yunjiao.springboot.extension.id.snowflakeDatacenterId'
----

如果不是微服务或集群部署应用，可以忽略此警告

[NOTE]
====
本框架提供的雪花ID工具，没有必要都使用，使用其中的一种就可以满足大部分场景
====

使用`CachedUidGeneratorConfigurer`自定义配置

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@Slf4j
@Configuration
public class IdConfiguration {

    @Bean
    CachedUidGeneratorConfigurer CachedUidGeneratorConfigurer() {
        return generator -> {
            log.info("自定义配置");
            generator.setBoostPower(3);
            generator.setPaddingFactor(50);
            generator.setScheduleInterval(60);
        };
    }

}
----




