DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       "name" VARCHAR(50) NOT NULL,
                       "email" VARCHAR(100),
                       "age" INT,
                       "birth_date" DATE,
                       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (1, 'zhangs', 'zhangs@company.com', 21, '2003-08-12', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (2, 'Michael Miller', 'michael.miller378@company.com', 21, '2004-08-12', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (3, 'Jennifer Garcia', 'jennifer.garcia828@outlook.com', 86, '1939-08-29', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (4, 'Linda Davis', 'linda.davis337@company.com', 70, '1955-08-25', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (5, 'Michael Miller', 'michael.miller724@gmail.com', 54, '1971-08-21', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (6, 'Robert Jones', 'robert.jones645@company.com', 51, '1974-08-20', '2025-08-07 20:30:58');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (7, 'David Hernandez', 'david.hernandez573@hotmail.com', 94, '1931-08-31', '2025-08-07 20:30:59');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (8, 'James Smith', 'james.smith102@yahoo.com', 96, '1929-08-31', '2025-08-07 20:30:59');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (9, 'Jessica Thomas', 'jessica.thomas991@outlook.com', 100, '1925-09-01', '2025-08-07 20:30:59');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (10, 'Michael Miller', 'michael.miller610@gmail.com', 23, '2002-08-13', '2025-08-07 20:30:59');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (791, 'David Hernandez', 'david.hernandez61@gmail.com', 33, '1992-08-15', '2025-08-07 20:31:00');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (416, 'David Hernandez', 'david.hernandez523@hotmail.com', 31, '1994-08-15', '2025-08-07 20:30:59');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (462, 'David Hernandez', 'david.hernandez514@hotmail.com', 19, '2006-08-12', '2025-08-07 20:31:00');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (783, 'David Hernandez', 'david.hernandez6@hotmail.com', 59, '1966-08-22', '2025-08-07 20:31:00');
INSERT INTO users ("id", "name", "email", "age", "birth_date", "created_at") VALUES (455, 'David Hernandez', 'david.hernandez843@yahoo.com', 99, '1925-09-01', '2025-08-07 20:31:00');

CREATE TABLE orders (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 101) PRIMARY KEY,
                        "user_id" BIGINT NOT NULL,
                        "status" VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','completed','cancelled','refunded')), -- DEFAULT moved before CHECK
                        "transaction_time" TIMESTAMP,
                        "amount" DECIMAL(10, 2),
                        CONSTRAINT "orders_ibfk_1" FOREIGN KEY ("user_id") REFERENCES users ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_user" ON orders ("user_id");
CREATE INDEX "idx_status" ON orders ("status");

INSERT INTO orders ("id", "user_id", "status", "transaction_time", "amount") VALUES (2, 5, 'completed', '2024-12-13 04:31:01', 3609.92);
INSERT INTO orders ("id", "user_id", "status", "transaction_time", "amount") VALUES (3, 3, 'cancelled', '2024-10-11 03:31:01', 951.05);
INSERT INTO orders ("id", "user_id", "status", "transaction_time", "amount") VALUES (4, 4, 'refunded', '2025-06-13 18:31:01', 1257.71);
INSERT INTO orders ("id", "user_id", "status", "transaction_time", "amount") VALUES (5, 5, 'completed', '2025-04-01 08:31:01', 2449.95);
