spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunjiao?userSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: debug
    io.yunjiao: debug
    com.querydsl.sql: debug # 打印SQL语句

